server {
    listen 8080;

    root /sgoinfre/mjong/myc/webserv/templates;

    location / {
        index index.html;
        autoindex on;
        allow_methods GET;
    }

    location /uploads {
        root /sgoinfre/mjong/myc/webserv/www;
        upload_store /sgoinfre/mjong/myc/webserv/www/uploads;
        allow_methods GET POST DELETE;
        autoindex on;
    }
}
